# HandWritten
跟着李沐的课程全部手写

Li Mu course notes and hands-on experiments.

In [19]:
import torch

张量表示由一个数值组成的数组，这个数组可能有多个维度

In [20]:
x = torch.arange(12)
print('x is' , x)

x is tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


可以通过张量的 shape 属性来访问张量的形状 和张量中元素的总数

In [21]:
x.shape

torch.Size([12])

In [22]:
x.numel()

12

In [23]:
X = x.reshape(3,4)#将x转换为一个新的二行六列矩阵
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0、全1、其他常量或者从特定分布中随机采样的数字

In [24]:
torch.zeros(2,3,4)#两个三行四列全零矩阵

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
torch.ones(2,3,4)#两个三行四列全零矩阵

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的 Python 列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [26]:
torch.tensor([[1,2,3,4],[2,2,3,4],[3,2,3,4]])

tensor([[1, 2, 3, 4],
        [2, 2, 3, 4],
        [3, 2, 3, 4]])

常见的标准算术运算符（+、-、*、/ 和 **）都可以被升级为按元素运算

In [27]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [28]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

我们也可以把多个张量 连结（concatenate） 在一起

In [29]:
#torch.arange(12)：生成 0 到 11
#dtype=torch.float32：把数据类型设成浮点数
#.reshape((3, 4))：改成 3 行 4 列
x = torch.arange(12, dtype=torch.float32).reshape((3,4))

#这是直接手工创建一个 3 x 4 的张量
y = torch.tensor([[1,2,3,4],[2,2,3,4],[3,2,3,11]])

#torch.cat 的意思是：把多个张量拼接起来。
#cat 是 concatenate 的缩写。
#dim=0 表示：按第 0 维拼，也就是“上下拼，增加行数”。
Z = torch.cat((x,y),dim = 0)

#dim=1 表示：按第 1 维拼，也就是“左右拼，增加列数”。
W = torch.cat((x,y),dim=1)
Z,W

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 2.,  2.,  3.,  4.],
         [ 3.,  2.,  3., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  2.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  3.,  2.,  3., 11.]]))

通过**逻辑运算符**构建二元张量

In [30]:
JUDGE = x==y
JUDGE

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]])

对张量中的所有元素进行求和会产生一个只有一个元素的张量

In [31]:
torch.sum(x)

tensor(66.)

即使形状不同，我们仍然可以通过调用 广播机制 （broadcasting mechanism） 来执行按元素操作

In [32]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [33]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用 [-1] 选择最后一个元素，可以用 [1:3] 选择第二个和第三个元素

In [34]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵

In [35]:
X[1,2]=100
X

tensor([[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值


In [37]:
X[0:2,:] =100
X

tensor([[100, 100, 100, 100],
        [100, 100, 100, 100],
        [  8,   9,  10,  11]])

运行一些操作可能会导致为新结果分配内存

In [41]:
before = id(X)
X = X + X
id(X) == before

False

执行原地操作

In [43]:
Z = torch.zeros_like(x)
print('id(Z):', id(Z))
Z[:] = X + x
print('id(Z):', id(Z))

id(Z): 2238091857104
id(Z): 2238091857104


如果在后续计算中没有重复使用 X，我们也可以使用 X[:] = X + Y 或 X += Y 来减少操作的内存开销