# 线性代数

一些基本的线性代数代码

In [1]:
import torch

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [2]:
x[3]

tensor(3)

In [3]:
len(x)

4

In [4]:
x.shape

torch.Size([4])

## 矩阵

In [5]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [6]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [7]:
A.T.shape

torch.Size([4, 5])

In [8]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 张量算法的基本性质

标量、向量、矩阵和任意数量轴的张量（本小节中的“张量”指代数对象）有一些实用的属性。
例如，从按元素操作的定义中可以注意到，任何按元素的一元运算都不会改变其操作数的形状。
同样，[**给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量**]。
例如，将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法。


In [11]:
A = torch.arange(20, dtype =torch.float32).reshape(5,4)
B = A.clone()# A和B数相同,但是内存地址不同
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [12]:
A*B#哈达玛积,对应元素乘积

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

## 降维

:label:`subseq_lin-alg-reduction`

我们可以对任意张量进行的一个有用的操作是[**计算其元素的和**]。
数学表示法使用$\sum$符号表示求和。
为了表示长度为$d$的向量中元素的总和，可以记为$\sum_{i=1}^dx_i$。
在代码中可以调用计算求和的函数：


In [19]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

我们可以(**表示任意形状张量的元素和**)。
例如，矩阵$\mathbf{A}$中元素的和可以记为$\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$。


In [14]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

指定`axis=1`将通过汇总所有列的元素降维（轴1）。因此，输入轴1的维数在输出形状中消失。


In [15]:
# axis=0: 对每一列求和
# 例如第一列所有数加起来，第二列所有数加起来……
A_sum_by_column = A.sum(axis=0)

# axis=1: 对每一行求和
# 例如第一行所有数加起来，第二行所有数加起来……
A_sum_by_row = A.sum(axis=1)

print("按列求和:", A_sum_by_column)
print("按列求和后的形状:", A_sum_by_column.shape)

print("按行求和:", A_sum_by_row)
print("按行求和后的形状:", A_sum_by_row.shape)

按列求和: tensor([40., 45., 50., 55.])
按列求和后的形状: torch.Size([4])
按行求和: tensor([ 6., 22., 38., 54., 70.])
按行求和后的形状: torch.Size([5])


[**一个与求和相关的量是*平均值*（mean或average）**]。
我们通过将总和除以元素总数来计算平均值。
在代码中，我们可以调用函数来计算任意形状张量的平均值。


In [16]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [17]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

### 非降维求和

:label:`subseq_lin-alg-non-reduction`

但是，有时在调用函数来[**计算总和或均值时保持轴数不变**]会很有用。


In [21]:
# 对矩阵 A 按行求和
# axis=1:
#   表示在列的方向上进行汇总
#   也就是“每一行内部的元素相加”
# keepdims=True:
#   表示保留原来的二维结构
#   所以结果不是 shape = (m,)
#   而是 shape = (m, 1)
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [22]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

## 点乘,向量积,略过了

## L1,L2范数,也略过了